runtime: php74

env_variables:
  ## Put production environment variables here.
  APP_KEY: base64:WHLAMtnUqZXwIjhTb8jPksef4y/CWkIHzyuEEjGGvUY=
  APP_STORAGE: /tmp
  VIEW_COMPILED_PATH: /tmp
  SESSION_DRIVER: cookie
